# Generated by Django 5.2.5 on 2025-08-10 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('tracking', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('en_deposito', 'En deposito'), ('en_distribucion', 'En distribucion')], default='en_deposito', max_length=20)),
                ('tipo_paquete', models.CharField(max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('motivo_fallo', models.CharField(blank=True, max_length=255, null=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paquete')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.planilla')),
            ],
        ),
    ]
